window.allProducts = [
  {
    "id": "1",
    "sku": "CB-4-8",
    "name": "Mdf Clock Base",
    "category": "MDF",
    "subcategory": "base",
    "tagweb": "resin, mdf",
    "brand": "Wooden Beyond",
    "attrName": "width,size",
    "attrValue": "4_mm, 8_inch",
    "tagline": "A clock base for your resin art work",
    "description": "good quality, semi pine, used in resin art work",
    "otherDetails": "",
    "mrp": "80",
    "sale": "74",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock base, mdf base, mdf",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEjfoEo46vUkOZjlwt62xNRNxK3SJiT6pHO9EpjlzrEzrC0_oHsVOipP4D4IffHGahRPIU062llR0sZiSt4eq6EJ35xmrUhqNARyg_NR128nTCq69CnvV4qJS1GmFzu-1HhMwb30un7mp7R0wCisPVwx-Yntygd9Y_Yru5mBKbHme9tsnj3pInlbBpl_8qgq"
    ],
    "vid": ""
  },
  {
    "id": "1",
    "sku": "CB-4-10",
    "name": "Mdf Clock Base",
    "category": "MDF",
    "subcategory": "base",
    "tagweb": "resin, mdf",
    "brand": "Wooden Beyond",
    "attrName": "width,size",
    "attrValue": "4_mm,10_inch",
    "tagline": "A clock base for your resin art work",
    "description": "good quality, semi pine, used in resin art work",
    "otherDetails": "",
    "mrp": "100",
    "sale": "91",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock base, mdf base, mdf",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj-JSpAegAqXjL7aUk9a-ANl0Y5aJHdy3t97jjIJGSdkF08Mcte3o3oGUK1r6Z_yJ9ZAUCJVmN33pWg4Sl0gI87md-mrYwnoqzeiFVPjvtQVuBRqzctRO5_BqIcHn-n9und4zLc9SSefOEbzu1Iu2qmFNpurOaI0tVR4femRiyjPaYO6ab73WtmKa6yV1F2/s1600/download.jpg",
      "https://blogger.googleusercontent.com/img/a/AVvXsEjfoEo46vUkOZjlwt62xNRNxK3SJiT6pHO9EpjlzrEzrC0_oHsVOipP4D4IffHGahRPIU062llR0sZiSt4eq6EJ35xmrUhqNARyg_NR128nTCq69CnvV4qJS1GmFzu-1HhMwb30un7mp7R0wCisPVwx-Yntygd9Y_Yru5mBKbHme9tsnj3pInlbBpl_8qgq"
    ],
    "vid": ""
  },
  {
    "id": "1",
    "sku": "CB-3-8",
    "name": "Mdf Clock Base",
    "category": "MDF",
    "subcategory": "base",
    "tagweb": "resin, mdf",
    "brand": "Wooden Beyond",
    "attrName": "width,size,breadth",
    "attrValue": "3_mm, 8_inch, 2_mm",
    "tagline": "A clock base for your resin art work",
    "description": "good quality, semi pine, used in resin art work",
    "otherDetails": "",
    "mrp": "75",
    "sale": "71",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock base, mdf base, mdf",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj-JSpAegAqXjL7aUk9a-ANl0Y5aJHdy3t97jjIJGSdkF08Mcte3o3oGUK1r6Z_yJ9ZAUCJVmN33pWg4Sl0gI87md-mrYwnoqzeiFVPjvtQVuBRqzctRO5_BqIcHn-n9und4zLc9SSefOEbzu1Iu2qmFNpurOaI0tVR4femRiyjPaYO6ab73WtmKa6yV1F2/s1600/download.jpg",
      "https://blogger.googleusercontent.com/img/a/AVvXsEjfoEo46vUkOZjlwt62xNRNxK3SJiT6pHO9EpjlzrEzrC0_oHsVOipP4D4IffHGahRPIU062llR0sZiSt4eq6EJ35xmrUhqNARyg_NR128nTCq69CnvV4qJS1GmFzu-1HhMwb30un7mp7R0wCisPVwx-Yntygd9Y_Yru5mBKbHme9tsnj3pInlbBpl_8qgq"
    ],
    "vid": ""
  },
  {
    "id": "2",
    "sku": "RC-4-8",
    "name": "Resin clock",
    "category": "Clock",
    "subcategory": "wall clock",
    "tagweb": "resin, homedecor",
    "brand": "Resin cosmos",
    "attrName": "Size",
    "attrValue": "8_inch",
    "tagline": "Premium Classic clock",
    "description": "Made With epoxy resin, Make your room premium",
    "otherDetails": "Material-Resin,Base-MDF,size-8inch",
    "mrp": "9999",
    "sale": "8999",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "TRUE",
    "kitName": "Clock kit",
    "kitComponents": "1,2,5,6,7",
    "keyword": "clock,watch,wall clock",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEgyB7_1XcP06iTzs51DMo2Al0o5lMKb0kmO1lt12MEcJ80IPbyzWOYTOzz26sZc9TXiPaUUTThAZb63A157obX6dO28s3TqaMBkN0bSEF9rWc4QaF77-BwFtEXJBFK-Z5BpBAUQy9VDHK8tVOxwcizAM1vDOnMZ6jJhUInxamsHwtFlnME1muaIyQ9hSoTE"
    ],
    "vid": ""
  },
  {
    "id": "3",
    "sku": "SM-K-R-12",
    "name": "Keychain mould",
    "category": "Silicone Mould",
    "subcategory": "keychain",
    "tagweb": "resin, mould",
    "brand": "Resin cosmos",
    "attrName": "pcs",
    "attrValue": "12",
    "tagline": "Keychain mould for resin art",
    "description": "12 keychain you can make at 1 time",
    "otherDetails": "",
    "mrp": "150",
    "sale": "139",
    "stock": "soldout",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "mould, keychain mould",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEjXns1diih_C8vVn60hVfBKN9YLJwgcXB7yv9s8b5WVRU31pObVaG0BTPI197FUUOuf5yM8vY8N0VgklychwFKfEBD7f-oZ6iqic3rOqal3mYtwNCg80pkBylA0vl9EzTM25o4mTqRCcmd8k-GVWxAvgYarkdOv4EG32uOpSfXjz5ivSfv0PV2RnKlEIAaz",
      "https://blogger.googleusercontent.com/img/a/AVvXsEgyB7_1XcP06iTzs51DMo2Al0o5lMKb0kmO1lt12MEcJ80IPbyzWOYTOzz26sZc9TXiPaUUTThAZb63A157obX6dO28s3TqaMBkN0bSEF9rWc4QaF77-BwFtEXJBFK-Z5BpBAUQy9VDHK8tVOxwcizAM1vDOnMZ6jJhUInxamsHwtFlnME1muaIyQ9hSoTE"
    ],
    "vid": ""
  },
  {
    "id": "4",
    "sku": "SM-DS-R-8",
    "name": "Rectangle Mould",
    "category": "Silicone Mould",
    "subcategory": "Deep casting",
    "tagweb": "resin, mould",
    "brand": "Resin cosmos",
    "attrName": "size",
    "attrValue": "8 inch",
    "tagline": "preserve your memories",
    "description": "Best quality silicon mould",
    "otherDetails": "",
    "mrp": "899",
    "sale": "449",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "deep preservation mould,mould,mold,square mould",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx",
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx"
    ],
    "vid": ""
  },
  {
    "id": "4",
    "sku": "SM-DS-R-4",
    "name": "Rectangle Mould",
    "category": "Silicone Mould",
    "subcategory": "Deep casting",
    "tagweb": "resin, mould",
    "brand": "Resin cosmos",
    "attrName": "size",
    "attrValue": "4 inch",
    "tagline": "preserve your memories",
    "description": "Best quality silicon mould",
    "otherDetails": "",
    "mrp": "499",
    "sale": "249",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "deep preservation mould,mould,mold,square mould",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx",
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx"
    ],
    "vid": ""
  },
  {
    "id": "5",
    "sku": "CS-BS",
    "name": "Clock Stricks",
    "category": "Raw material",
    "subcategory": "Clock",
    "tagweb": "resin, art",
    "brand": "",
    "attrName": "",
    "attrValue": "",
    "tagline": "good looking clock stirkes (2 minutes and hours)",
    "description": "Get Good looking stricks for your clock",
    "otherDetails": "",
    "mrp": "50",
    "sale": "29",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock material, clock strike",
    "trending": "FALSE",
    "delivery": "",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEh0RTX5T0PYDGPaj5YA8fx6C39-TDy1yQSlXsJyWeEpTb9bAyhPQFvc5axhp4RY635O76xHo3kfagRsc0F6SEDkx42hAnkwJfk5wEBONQx5YyEYO-OCzY3c9pBAPZc4brzw0_EaE7HvFtv3vZlg_y1YzAAR4VFTzvmfoUeiu9lLbKv-eJYpmzlK1pZH2u9-",
      "https://blogger.googleusercontent.com/img/a/AVvXsEh0RTX5T0PYDGPaj5YA8fx6C39-TDy1yQSlXsJyWeEpTb9bAyhPQFvc5axhp4RY635O76xHo3kfagRsc0F6SEDkx42hAnkwJfk5wEBONQx5YyEYO-OCzY3c9pBAPZc4brzw0_EaE7HvFtv3vZlg_y1YzAAR4VFTzvmfoUeiu9lLbKv-eJYpmzlK1pZH2u9-"
    ],
    "vid": ""
  },
  {
    "id": "6",
    "sku": "CM-B-18",
    "name": "Clock machine",
    "category": "Raw material",
    "subcategory": "Clock",
    "tagweb": "resin, art",
    "brand": "",
    "attrName": "size",
    "attrValue": "18 mm",
    "tagline": "Tick Clock machine",
    "description": "",
    "otherDetails": "",
    "mrp": "69",
    "sale": "59",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock machine",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr",
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr"
    ],
    "vid": ""
  },
  {
    "id": "6",
    "sku": "CM-B-14",
    "name": "Clock machine",
    "category": "Raw material",
    "subcategory": "Clock",
    "tagweb": "resin, art",
    "brand": "",
    "attrName": "size",
    "attrValue": "14 mm",
    "tagline": "Tick Clock machine",
    "description": "",
    "otherDetails": "",
    "mrp": "69",
    "sale": "59",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock machine",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr",
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr"
    ],
    "vid": ""
  },
  {
    "id": "7",
    "sku": "CM-S-S",
    "name": "Clock hanger",
    "category": "Raw material",
    "subcategory": "Clock",
    "tagweb": "resin",
    "brand": "",
    "attrName": "",
    "attrValue": "",
    "tagline": "hange you clock",
    "description": "still",
    "otherDetails": "",
    "mrp": "20",
    "sale": "19",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock hanger",
    "trending": "FALSE",
    "delivery": "",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEiHMhaWo-8BDn65nTSCykubvyEaN_pKakUM7byuXdvzdIEMijBloMT6189DdvjD0zps2DUSjw6EzjqDg040ErnEzSU9nnsRdU8RDOaq4wT5HEuaBTzy6df15FqsvxWBPk_G0NdW1JTXmy9XVc6FnvEn5JY4rhjING2uYdgTrw_g16Hk8RCHm60TAGSTqUHc",
      "https://blogger.googleusercontent.com/img/a/AVvXsEiHMhaWo-8BDn65nTSCykubvyEaN_pKakUM7byuXdvzdIEMijBloMT6189DdvjD0zps2DUSjw6EzjqDg040ErnEzSU9nnsRdU8RDOaq4wT5HEuaBTzy6df15FqsvxWBPk_G0NdW1JTXmy9XVc6FnvEn5JY4rhjING2uYdgTrw_g16Hk8RCHm60TAGSTqUHc"
    ],
    "vid": ""
  },
  {
    "id": "8",
    "sku": "AL-G-12-1",
    "name": "golden acrylic later",
    "category": "Raw material",
    "subcategory": "Clock",
    "tagweb": "resin, acrylic",
    "brand": "acrylic fortune",
    "attrName": "size,latter",
    "attrValue": "1 inch,12",
    "tagline": "customize your clock with our premium latter",
    "description": "12 latter 1mm tjick",
    "otherDetails": "",
    "mrp": "99",
    "sale": "89",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock latter, twelve latter",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEjqdPAj3fGAM8ct6zybaXEkCiKA8geIKijntbRFZD1ypYXk_h-HiDHN9Pg8Pnmtw3hMGsMfpYPILPQEY0xqUBU4Q1_AEl1v9obzrHcQMQvRJi_12oYQjJ9UYJkiPMVDTJGI05FJ7UwMzQ9RzMAWaYYGMCoADA3IedVxWxpP8Aq8GZXF6H8ZCkh5Cq9UseYI",
      "https://blogger.googleusercontent.com/img/a/AVvXsEjqdPAj3fGAM8ct6zybaXEkCiKA8geIKijntbRFZD1ypYXk_h-HiDHN9Pg8Pnmtw3hMGsMfpYPILPQEY0xqUBU4Q1_AEl1v9obzrHcQMQvRJi_12oYQjJ9UYJkiPMVDTJGI05FJ7UwMzQ9RzMAWaYYGMCoADA3IedVxWxpP8Aq8GZXF6H8ZCkh5Cq9UseYI"
    ],
    "vid": ""
  },
  {
    "id": "9",
    "sku": "AL-G-RW-1",
    "name": "Love cutout",
    "category": "Raw material",
    "subcategory": "Art",
    "tagweb": "acrylic",
    "brand": "acrylic fortune",
    "attrName": "size",
    "attrValue": "4 inch",
    "tagline": "customize yours",
    "description": "acrylic made",
    "otherDetails": "",
    "mrp": "199",
    "sale": "149",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "latter",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEiVtWg2zAq12Hn81SncG1lUp12cMawXzbW8e7dFVGgN7EKmkWOOFbDKbxAAo0WPM7swjqcUB8ybKC9Obu4bKR4dpQtLneEyBuIeVbatfCnPg_FAC189M9jKZScT0gSaXeDYopk1u_YXJAbbh5sK9bc3XdJ6zrcDNomMuJXNL7KNEBzpfNwsFiPYsgMk9jYS",
      "https://blogger.googleusercontent.com/img/a/AVvXsEiVtWg2zAq12Hn81SncG1lUp12cMawXzbW8e7dFVGgN7EKmkWOOFbDKbxAAo0WPM7swjqcUB8ybKC9Obu4bKR4dpQtLneEyBuIeVbatfCnPg_FAC189M9jKZScT0gSaXeDYopk1u_YXJAbbh5sK9bc3XdJ6zrcDNomMuJXNL7KNEBzpfNwsFiPYsgMk9jYS"
    ],
    "vid": ""
  }
];

window.dispatchEvent(new Event('db_ready'));