window.allProducts = [
  {
    "id": "1",
    "sku": "CB-4-8",
    "name": "Mdf Clock Base",
    "category": "MDF",
    "subcategory": "base",
    "tagweb": "resin,mdf,raw",
    "brand": "Wooden Beyond",
    "attrName": "width,size",
    "attrValue": "4_mm, 8_inch",
    "tagline": "A clock base for your resin art work",
    "description": "good quality, semi pine, used in resin art work",
    "otherDetails": "",
    "mrp": "80",
    "sale": "74",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock base, mdf base, mdf",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEjfoEo46vUkOZjlwt62xNRNxK3SJiT6pHO9EpjlzrEzrC0_oHsVOipP4D4IffHGahRPIU062llR0sZiSt4eq6EJ35xmrUhqNARyg_NR128nTCq69CnvV4qJS1GmFzu-1HhMwb30un7mp7R0wCisPVwx-Yntygd9Y_Yru5mBKbHme9tsnj3pInlbBpl_8qgq",
      "https://blogger.googleusercontent.com/img/a/AVvXsEjfoEo46vUkOZjlwt62xNRNxK3SJiT6pHO9EpjlzrEzrC0_oHsVOipP4D4IffHGahRPIU062llR0sZiSt4eq6EJ35xmrUhqNARyg_NR128nTCq69CnvV4qJS1GmFzu-1HhMwb30un7mp7R0wCisPVwx-Yntygd9Y_Yru5mBKbHme9tsnj3pInlbBpl_8qgq"
    ],
    "vid": ""
  },
  {
    "id": "1",
    "sku": "CB-4-10",
    "name": "Mdf Clock Base",
    "category": "MDF",
    "subcategory": "base",
    "tagweb": "resin,mdf,raw",
    "brand": "Wooden Beyond",
    "attrName": "width,size",
    "attrValue": "4_mm,10_inch",
    "tagline": "A clock base for your resin art work",
    "description": "good quality, semi pine, used in resin art work",
    "otherDetails": "",
    "mrp": "100",
    "sale": "91",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock base, mdf base, mdf",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj-JSpAegAqXjL7aUk9a-ANl0Y5aJHdy3t97jjIJGSdkF08Mcte3o3oGUK1r6Z_yJ9ZAUCJVmN33pWg4Sl0gI87md-mrYwnoqzeiFVPjvtQVuBRqzctRO5_BqIcHn-n9und4zLc9SSefOEbzu1Iu2qmFNpurOaI0tVR4femRiyjPaYO6ab73WtmKa6yV1F2/s1600/download.jpg",
      "https://blogger.googleusercontent.com/img/a/AVvXsEjfoEo46vUkOZjlwt62xNRNxK3SJiT6pHO9EpjlzrEzrC0_oHsVOipP4D4IffHGahRPIU062llR0sZiSt4eq6EJ35xmrUhqNARyg_NR128nTCq69CnvV4qJS1GmFzu-1HhMwb30un7mp7R0wCisPVwx-Yntygd9Y_Yru5mBKbHme9tsnj3pInlbBpl_8qgq"
    ],
    "vid": ""
  },
  {
    "id": "1",
    "sku": "CB-3-8",
    "name": "Mdf Clock Base",
    "category": "MDF",
    "subcategory": "base",
    "tagweb": "resin,mdf,raw",
    "brand": "Wooden Beyond",
    "attrName": "width,size",
    "attrValue": "3_mm, 8_inch",
    "tagline": "A clock base for your resin art work",
    "description": "good quality, semi pine, used in resin art work",
    "otherDetails": "",
    "mrp": "75",
    "sale": "71",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock base, mdf base, mdf",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj-JSpAegAqXjL7aUk9a-ANl0Y5aJHdy3t97jjIJGSdkF08Mcte3o3oGUK1r6Z_yJ9ZAUCJVmN33pWg4Sl0gI87md-mrYwnoqzeiFVPjvtQVuBRqzctRO5_BqIcHn-n9und4zLc9SSefOEbzu1Iu2qmFNpurOaI0tVR4femRiyjPaYO6ab73WtmKa6yV1F2/s1600/download.jpg",
      "https://blogger.googleusercontent.com/img/a/AVvXsEjfoEo46vUkOZjlwt62xNRNxK3SJiT6pHO9EpjlzrEzrC0_oHsVOipP4D4IffHGahRPIU062llR0sZiSt4eq6EJ35xmrUhqNARyg_NR128nTCq69CnvV4qJS1GmFzu-1HhMwb30un7mp7R0wCisPVwx-Yntygd9Y_Yru5mBKbHme9tsnj3pInlbBpl_8qgq"
    ],
    "vid": ""
  },
  {
    "id": "2",
    "sku": "RC-4-8",
    "name": "Resin clock",
    "category": "Clock",
    "subcategory": "wall clock",
    "tagweb": "resin,homedecor,ready",
    "brand": "Resin cosmos",
    "attrName": "Size",
    "attrValue": "8_inch",
    "tagline": "Premium Classic clock",
    "description": "Made With epoxy resin, Make your room premium",
    "otherDetails": "Material-Resin,Base-MDF,size-8inch",
    "mrp": "9999",
    "sale": "8999",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "TRUE",
    "kitName": "Clock kit",
    "kitComponents": "1,2,5,6,7",
    "keyword": "clock,watch,wall clock",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEgyB7_1XcP06iTzs51DMo2Al0o5lMKb0kmO1lt12MEcJ80IPbyzWOYTOzz26sZc9TXiPaUUTThAZb63A157obX6dO28s3TqaMBkN0bSEF9rWc4QaF77-BwFtEXJBFK-Z5BpBAUQy9VDHK8tVOxwcizAM1vDOnMZ6jJhUInxamsHwtFlnME1muaIyQ9hSoTE"
    ],
    "vid": ""
  },
  {
    "id": "3",
    "sku": "SM-K-R-12",
    "name": "Keychain mould",
    "category": "Silicone Mould",
    "subcategory": "keychain",
    "tagweb": "resin,mould,raw",
    "brand": "Resin cosmos",
    "attrName": "pcs",
    "attrValue": "12",
    "tagline": "Keychain mould for resin art",
    "description": "12 keychain you can make at 1 time",
    "otherDetails": "",
    "mrp": "150",
    "sale": "139",
    "stock": "soldout",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "mould, keychain mould",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEjXns1diih_C8vVn60hVfBKN9YLJwgcXB7yv9s8b5WVRU31pObVaG0BTPI197FUUOuf5yM8vY8N0VgklychwFKfEBD7f-oZ6iqic3rOqal3mYtwNCg80pkBylA0vl9EzTM25o4mTqRCcmd8k-GVWxAvgYarkdOv4EG32uOpSfXjz5ivSfv0PV2RnKlEIAaz",
      "https://blogger.googleusercontent.com/img/a/AVvXsEgyB7_1XcP06iTzs51DMo2Al0o5lMKb0kmO1lt12MEcJ80IPbyzWOYTOzz26sZc9TXiPaUUTThAZb63A157obX6dO28s3TqaMBkN0bSEF9rWc4QaF77-BwFtEXJBFK-Z5BpBAUQy9VDHK8tVOxwcizAM1vDOnMZ6jJhUInxamsHwtFlnME1muaIyQ9hSoTE"
    ],
    "vid": ""
  },
  {
    "id": "4",
    "sku": "SM-DS-R-8",
    "name": "Rectangle Mould",
    "category": "Silicone Mould",
    "subcategory": "Deep casting",
    "tagweb": "resin,mould,raw",
    "brand": "Resin cosmos",
    "attrName": "size",
    "attrValue": "8 inch",
    "tagline": "preserve your memories",
    "description": "Best quality silicon mould",
    "otherDetails": "",
    "mrp": "899",
    "sale": "449",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "deep preservation mould,mould,mold,square mould",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx",
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx"
    ],
    "vid": ""
  },
  {
    "id": "4",
    "sku": "SM-DS-R-4",
    "name": "Rectangle Mould",
    "category": "Silicone Mould",
    "subcategory": "Deep casting",
    "tagweb": "resin,mould,raw",
    "brand": "Resin cosmos",
    "attrName": "size",
    "attrValue": "4 inch",
    "tagline": "preserve your memories",
    "description": "Best quality silicon mould",
    "otherDetails": "",
    "mrp": "499",
    "sale": "249",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "deep preservation mould,mould,mold,square mould",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx",
      "https://blogger.googleusercontent.com/img/a/AVvXsEgik8w6EE_WNpk4kEi3nV1tpXNbtw4lSaHrR8Yetj6QbIBHjuvZzGv-sOkqKSwYEwxL_l8_YR7uDwGMor6I9k1tJpsOl7lPvzbVG1y3oFiqiM2dvK3FquRIUS0gxuvzeuuHKUILmjyUrA7u_Fnvlvj_GCYYFsobQ5hW7oDcWUdBNjZtOacPPveffzoM_tMx"
    ],
    "vid": ""
  },
  {
    "id": "5",
    "sku": "CS-BS",
    "name": "Clock Stricks",
    "category": "Raw material",
    "subcategory": "Components",
    "tagweb": "resin,raw",
    "brand": "",
    "attrName": "",
    "attrValue": "",
    "tagline": "good looking clock stirkes (2 minutes and hours)",
    "description": "Get Good looking stricks for your clock",
    "otherDetails": "",
    "mrp": "50",
    "sale": "29",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock material, clock strike",
    "trending": "FALSE",
    "delivery": "",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEh0RTX5T0PYDGPaj5YA8fx6C39-TDy1yQSlXsJyWeEpTb9bAyhPQFvc5axhp4RY635O76xHo3kfagRsc0F6SEDkx42hAnkwJfk5wEBONQx5YyEYO-OCzY3c9pBAPZc4brzw0_EaE7HvFtv3vZlg_y1YzAAR4VFTzvmfoUeiu9lLbKv-eJYpmzlK1pZH2u9-",
      "https://blogger.googleusercontent.com/img/a/AVvXsEh0RTX5T0PYDGPaj5YA8fx6C39-TDy1yQSlXsJyWeEpTb9bAyhPQFvc5axhp4RY635O76xHo3kfagRsc0F6SEDkx42hAnkwJfk5wEBONQx5YyEYO-OCzY3c9pBAPZc4brzw0_EaE7HvFtv3vZlg_y1YzAAR4VFTzvmfoUeiu9lLbKv-eJYpmzlK1pZH2u9-"
    ],
    "vid": ""
  },
  {
    "id": "6",
    "sku": "CM-B-18",
    "name": "Clock machine",
    "category": "Raw material",
    "subcategory": "Components",
    "tagweb": "resin,art",
    "brand": "",
    "attrName": "size",
    "attrValue": "18 mm",
    "tagline": "Tick Clock machine",
    "description": "",
    "otherDetails": "",
    "mrp": "69",
    "sale": "59",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock machine",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr",
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr"
    ],
    "vid": ""
  },
  {
    "id": "6",
    "sku": "CM-B-14",
    "name": "Clock machine",
    "category": "Raw material",
    "subcategory": "Components",
    "tagweb": "resin,art",
    "brand": "",
    "attrName": "size",
    "attrValue": "14 mm",
    "tagline": "Tick Clock machine",
    "description": "",
    "otherDetails": "",
    "mrp": "69",
    "sale": "59",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock machine",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr",
      "https://blogger.googleusercontent.com/img/a/AVvXsEhS6RY1wBE2UsoPSJXVXNlMxcKiX5Wnbg4ApK3gF8FQn357FONowNF4EGYvEr1zXKjIYvWA20LcQMYmHkdfUNYksKphJfjaCaE6zUy2cF3zXmLhcuknqXoWVQaSFXEzJzvxsnmWk8fCgz7ceIptXemwv6tmg6CxAcaq8Gy2rX5O99VgjzsxvExXG_qajsWr"
    ],
    "vid": ""
  },
  {
    "id": "7",
    "sku": "CM-S-S",
    "name": "Clock hanger",
    "category": "Raw material",
    "subcategory": "Components",
    "tagweb": "resin",
    "brand": "",
    "attrName": "",
    "attrValue": "",
    "tagline": "hange you clock",
    "description": "still",
    "otherDetails": "",
    "mrp": "20",
    "sale": "19",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock hanger",
    "trending": "FALSE",
    "delivery": "",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEiHMhaWo-8BDn65nTSCykubvyEaN_pKakUM7byuXdvzdIEMijBloMT6189DdvjD0zps2DUSjw6EzjqDg040ErnEzSU9nnsRdU8RDOaq4wT5HEuaBTzy6df15FqsvxWBPk_G0NdW1JTXmy9XVc6FnvEn5JY4rhjING2uYdgTrw_g16Hk8RCHm60TAGSTqUHc",
      "https://blogger.googleusercontent.com/img/a/AVvXsEiHMhaWo-8BDn65nTSCykubvyEaN_pKakUM7byuXdvzdIEMijBloMT6189DdvjD0zps2DUSjw6EzjqDg040ErnEzSU9nnsRdU8RDOaq4wT5HEuaBTzy6df15FqsvxWBPk_G0NdW1JTXmy9XVc6FnvEn5JY4rhjING2uYdgTrw_g16Hk8RCHm60TAGSTqUHc"
    ],
    "vid": ""
  },
  {
    "id": "8",
    "sku": "AL-G-12-1",
    "name": "golden acrylic later",
    "category": "Raw material",
    "subcategory": "Components",
    "tagweb": "resin, acrylic",
    "brand": "acrylic fortune",
    "attrName": "size,latter",
    "attrValue": "1 inch,12",
    "tagline": "customize your clock with our premium latter",
    "description": "12 latter 1mm tjick",
    "otherDetails": "",
    "mrp": "99",
    "sale": "89",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "clock latter, twelve latter",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEjqdPAj3fGAM8ct6zybaXEkCiKA8geIKijntbRFZD1ypYXk_h-HiDHN9Pg8Pnmtw3hMGsMfpYPILPQEY0xqUBU4Q1_AEl1v9obzrHcQMQvRJi_12oYQjJ9UYJkiPMVDTJGI05FJ7UwMzQ9RzMAWaYYGMCoADA3IedVxWxpP8Aq8GZXF6H8ZCkh5Cq9UseYI",
      "https://blogger.googleusercontent.com/img/a/AVvXsEjqdPAj3fGAM8ct6zybaXEkCiKA8geIKijntbRFZD1ypYXk_h-HiDHN9Pg8Pnmtw3hMGsMfpYPILPQEY0xqUBU4Q1_AEl1v9obzrHcQMQvRJi_12oYQjJ9UYJkiPMVDTJGI05FJ7UwMzQ9RzMAWaYYGMCoADA3IedVxWxpP8Aq8GZXF6H8ZCkh5Cq9UseYI"
    ],
    "vid": ""
  },
  {
    "id": "9",
    "sku": "AL-G-RW-1",
    "name": "Love cutout",
    "category": "Raw material",
    "subcategory": "Art",
    "tagweb": "acrylic",
    "brand": "acrylic fortune",
    "attrName": "size",
    "attrValue": "4 inch",
    "tagline": "customize yours",
    "description": "acrylic made",
    "otherDetails": "",
    "mrp": "199",
    "sale": "149",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "latter",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEiVtWg2zAq12Hn81SncG1lUp12cMawXzbW8e7dFVGgN7EKmkWOOFbDKbxAAo0WPM7swjqcUB8ybKC9Obu4bKR4dpQtLneEyBuIeVbatfCnPg_FAC189M9jKZScT0gSaXeDYopk1u_YXJAbbh5sK9bc3XdJ6zrcDNomMuJXNL7KNEBzpfNwsFiPYsgMk9jYS",
      "https://blogger.googleusercontent.com/img/a/AVvXsEiVtWg2zAq12Hn81SncG1lUp12cMawXzbW8e7dFVGgN7EKmkWOOFbDKbxAAo0WPM7swjqcUB8ybKC9Obu4bKR4dpQtLneEyBuIeVbatfCnPg_FAC189M9jKZScT0gSaXeDYopk1u_YXJAbbh5sK9bc3XdJ6zrcDNomMuJXNL7KNEBzpfNwsFiPYsgMk9jYS"
    ],
    "vid": ""
  },
  {
    "id": "G1",
    "sku": "GF-G-R",
    "name": "Ganpati Resin art",
    "category": "resin frame",
    "subcategory": "god",
    "tagweb": "resin,ready,custom,gift,frame",
    "brand": "Resin Cosmos",
    "attrName": "Size,Width",
    "attrValue": "8 mm,5 inch",
    "tagline": "a ganesha frame for table",
    "description": "5 inch size with stand,creative god frame",
    "otherDetails": "",
    "mrp": "500",
    "sale": "349",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "resin frame,ganesh,ganapati,art,",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgi2vhOT1RaumN7I2SWmwpZhH748rgkpEQ2aYCuNLBPkKPJp-pml8F8blWpzjPF8seodhCLDgm7L-Q7aH-PBtLoVyL1v1uqlUn9Y0A-qm2P2BTAPEzgzgxbJeawsQYSA-Gtb39UidlhgXwIlrX7Kj3cD3gUI_PayG4OO3WBhEqBE4McbMYfEhedE85MwDDl/w180-h320/IMG_1529.HEIC"
    ],
    "vid": ""
  },
  {
    "id": "ER1",
    "sku": "ER-1-1",
    "name": "Art Epoxy Resin 1:1",
    "category": "Resin",
    "subcategory": "Epoxy",
    "tagweb": "resin.raw",
    "brand": "Resin Cosmos",
    "attrName": "weight",
    "attrValue": "1kg",
    "tagline": "Art Epoxy resin make your Art real",
    "description": "1:1 Resin, mix properly before puor",
    "otherDetails": "",
    "mrp": "10",
    "sale": "1",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "Resin,art resin.,respin cosmos, 1kg resin",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBNCyRiO61XNjWvg66960Qa3N08jknQZuDMt2tCgVW3X204pmZVF1Ex2OM0NKCVIK9Qgz9OOuvIHQcaNO4T1QUEsp-H7mk-CXIkUiomAwi4QQm57m69U16GnB5Om19a8rUZBB0XjCYJbYeWKIMBZLFbQDiXd1JIFSsTv8FXvpRo8yJ-Ea0Bc3_I06vEYYy/s320/Gemini_Generated_Image_fatp7ofatp7ofatp.png"
    ],
    "vid": ""
  },
  {
    "id": "ER1",
    "sku": "ER-1-1.2",
    "name": "Art Epoxy Resin 1:2",
    "category": "Resin",
    "subcategory": "Epoxy",
    "tagweb": "resin.raw",
    "brand": "Resin Cosmos",
    "attrName": "weight",
    "attrValue": "1.2kg",
    "tagline": "Art Epoxy resin make your Art real",
    "description": "1:2 Resin, mix properly before puor",
    "otherDetails": "",
    "mrp": "12",
    "sale": "2",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "Resin,art resin.,respin cosmos, 1kg resin",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBNCyRiO61XNjWvg66960Qa3N08jknQZuDMt2tCgVW3X204pmZVF1Ex2OM0NKCVIK9Qgz9OOuvIHQcaNO4T1QUEsp-H7mk-CXIkUiomAwi4QQm57m69U16GnB5Om19a8rUZBB0XjCYJbYeWKIMBZLFbQDiXd1JIFSsTv8FXvpRo8yJ-Ea0Bc3_I06vEYYy/s320/Gemini_Generated_Image_fatp7ofatp7ofatp.png"
    ],
    "vid": ""
  },
  {
    "id": "ER1",
    "sku": "ER-1-1.5",
    "name": "Art Epoxy Resin 1:2",
    "category": "Resin",
    "subcategory": "Epoxy",
    "tagweb": "resin.raw",
    "brand": "Resin Cosmos",
    "attrName": "weight",
    "attrValue": "1.5kg",
    "tagline": "Art Epoxy resin make your Art real",
    "description": "1:2 Resin, mix properly before puor",
    "otherDetails": "",
    "mrp": "13",
    "sale": "3",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "Resin,art resin.,respin cosmos, 1kg resin",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBNCyRiO61XNjWvg66960Qa3N08jknQZuDMt2tCgVW3X204pmZVF1Ex2OM0NKCVIK9Qgz9OOuvIHQcaNO4T1QUEsp-H7mk-CXIkUiomAwi4QQm57m69U16GnB5Om19a8rUZBB0XjCYJbYeWKIMBZLFbQDiXd1JIFSsTv8FXvpRo8yJ-Ea0Bc3_I06vEYYy/s320/Gemini_Generated_Image_fatp7ofatp7ofatp.png"
    ],
    "vid": ""
  },
  {
    "id": "ER1",
    "sku": "ER-1-2",
    "name": "Art Epoxy Resin 1:3",
    "category": "Resin",
    "subcategory": "Epoxy",
    "tagweb": "resin.raw",
    "brand": "Resin Cosmos",
    "attrName": "weight",
    "attrValue": "2kg",
    "tagline": "Art Epoxy resin make your Art real",
    "description": "1:2 Resin, mix properly before puor",
    "otherDetails": "",
    "mrp": "14",
    "sale": "4",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "Resin,art resin.,respin cosmos, 1kg resin",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBNCyRiO61XNjWvg66960Qa3N08jknQZuDMt2tCgVW3X204pmZVF1Ex2OM0NKCVIK9Qgz9OOuvIHQcaNO4T1QUEsp-H7mk-CXIkUiomAwi4QQm57m69U16GnB5Om19a8rUZBB0XjCYJbYeWKIMBZLFbQDiXd1JIFSsTv8FXvpRo8yJ-Ea0Bc3_I06vEYYy/s320/Gemini_Generated_Image_fatp7ofatp7ofatp.png"
    ],
    "vid": ""
  },
  {
    "id": "UR1",
    "sku": "UV-R-1-10",
    "name": "UV Resin",
    "category": "Resin",
    "subcategory": "Uv",
    "tagweb": "resin.raw",
    "brand": "Resin Cosmos",
    "attrName": "weight",
    "attrValue": "10g",
    "tagline": "UV resin Pour With UV light",
    "description": "",
    "otherDetails": "",
    "mrp": "10",
    "sale": "1",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "",
    "kitComponents": "",
    "keyword": "Uv Resin,uv,resin,kit",
    "trending": "FALSE",
    "delivery": "TRUE",
    "images": [
      "https://blogger.googleusercontent.com/img/a/AVvXsEjwNxEqsW9cT6kDDUtcSjL2UWF6mhBcRuDGfQL9TrS093psN78woOmdsVQDmQIJCfNH4kJHFYYtyT2okZxbZqil2z8Eo3yfS1NeeAI5dRUeXqrX-YkoM7BWkE3s1lr33EUoZvJOWtkJfNb5IaH3yIeHEsbMTc1gSsCv8W-woy1LtE7URULb-bL4babJvR_7"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-GOLD-G-10",
    "name": "24K Gold Mica 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Gold,10g",
    "tagline": "Shine like real gold",
    "description": "Premium metallic, gold pigment, non-toxic",
    "otherDetails": "10g jar, 10-60 microns",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "gold,mica,resin,pigment,metallic",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/gold-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-GOLD-G-25",
    "name": "24K Gold Mica 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Gold,25g",
    "tagline": "Shine like real gold",
    "description": "Premium metallic, gold pigment, non-toxic",
    "otherDetails": "25g jar, 10-60 microns",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "gold,mica,resin,pigment,metallic",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/gold-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-GOLD-G-50",
    "name": "24K Gold Mica 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Gold,50g",
    "tagline": "Shine like real gold",
    "description": "Premium metallic, gold pigment, non-toxic",
    "otherDetails": "50g jar, 10-60 microns",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "gold,mica,resin,pigment,metallic",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/gold-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-SILV-S-10",
    "name": "Silver Chrome 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Silver,10g",
    "tagline": "Polished silver finish",
    "description": "Brilliant mirror effect, silver color, bubble-free",
    "otherDetails": "10g jar, fine particle",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "silver,mica,chrome,resin,metallic",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/silver-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-SILV-S-25",
    "name": "Silver Chrome 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Silver,25g",
    "tagline": "Polished silver finish",
    "description": "Brilliant mirror effect, silver color, bubble-free",
    "otherDetails": "25g jar, fine particle",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "silver,mica,chrome,resin,metallic",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/silver-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-SILV-S-50",
    "name": "Silver Chrome 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Silver,50g",
    "tagline": "Polished silver finish",
    "description": "Brilliant mirror effect, silver color, bubble-free",
    "otherDetails": "50g jar, fine particle",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "silver,mica,chrome,resin,metallic",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/silver-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RBLU-B-10",
    "name": "Royal Blue 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Blue,10g",
    "tagline": "Deep ocean mystery",
    "description": "Vibrant blue color, pearl finish, stain-free",
    "otherDetails": "10g jar, easy mix",
    "mrp": "10",
    "sale": "7",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "blue,ocean,mica,resin,pearl",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/blue-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RBLU-B-25",
    "name": "Royal Blue 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Blue,25g",
    "tagline": "Deep ocean mystery",
    "description": "Vibrant blue color, pearl finish, stain-free",
    "otherDetails": "25g jar, easy mix",
    "mrp": "20",
    "sale": "14",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "blue,ocean,mica,resin,pearl",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/blue-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RBLU-B-50",
    "name": "Royal Blue 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Blue,50g",
    "tagline": "Deep ocean mystery",
    "description": "Vibrant blue color, pearl finish, stain-free",
    "otherDetails": "50g jar, easy mix",
    "mrp": "35",
    "sale": "25",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "blue,ocean,mica,resin,pearl",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/blue-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-FGRN-G-10",
    "name": "Forest Green 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Green,10g",
    "tagline": "Lush nature tones",
    "description": "Emerald green color, eco-friendly, UV safe",
    "otherDetails": "10g jar, mineral base",
    "mrp": "10",
    "sale": "7",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "green,forest,mica,resin,emerald",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/green-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-FGRN-G-25",
    "name": "Forest Green 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Green,25g",
    "tagline": "Lush nature tones",
    "description": "Emerald green color, eco-friendly, UV safe",
    "otherDetails": "25g jar, mineral base",
    "mrp": "20",
    "sale": "14",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "green,forest,mica,resin,emerald",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/green-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-FGRN-G-50",
    "name": "Forest Green 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Green,50g",
    "tagline": "Lush nature tones",
    "description": "Emerald green color, eco-friendly, UV safe",
    "otherDetails": "50g jar, mineral base",
    "mrp": "35",
    "sale": "25",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "green,forest,mica,resin,emerald",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/green-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RUBY-R-10",
    "name": "Ruby Red 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Red,10g",
    "tagline": "Passionate red sparkle",
    "description": "Intense red color, high-gloss, premium mica",
    "otherDetails": "10g jar, ruby shade",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "red,ruby,sparkle,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/red-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RUBY-R-25",
    "name": "Ruby Red 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Red,25g",
    "tagline": "Passionate red sparkle",
    "description": "Intense red color, high-gloss, premium mica",
    "otherDetails": "25g jar, ruby shade",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "red,ruby,sparkle,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/red-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RUBY-R-50",
    "name": "Ruby Red 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Red,50g",
    "tagline": "Passionate red sparkle",
    "description": "Intense red color, high-gloss, premium mica",
    "otherDetails": "50g jar, ruby shade",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "red,ruby,sparkle,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/red-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-ONYX-B-10",
    "name": "Onyx Black 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Black,10g",
    "tagline": "Deep space darkness",
    "description": "Solid black color, opaque, midnight shimmer",
    "otherDetails": "10g jar, carbon grade",
    "mrp": "10",
    "sale": "7",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "black,onyx,space,resin,pigment",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/black-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-ONYX-B-25",
    "name": "Onyx Black 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Black,25g",
    "tagline": "Deep space darkness",
    "description": "Solid black color, opaque, midnight shimmer",
    "otherDetails": "25g jar, carbon grade",
    "mrp": "20",
    "sale": "14",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "black,onyx,space,resin,pigment",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/black-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-ONYX-B-50",
    "name": "Onyx Black 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Black,50g",
    "tagline": "Deep space darkness",
    "description": "Solid black color, opaque, midnight shimmer",
    "otherDetails": "50g jar, carbon grade",
    "mrp": "35",
    "sale": "25",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "black,onyx,space,resin,pigment",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/black-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-PRLW-W-10",
    "name": "Pearl White 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "White,10g",
    "tagline": "Elegant satin finish",
    "description": "Shimmering white color, pearl effect, pure",
    "otherDetails": "10g jar, satin finish",
    "mrp": "10",
    "sale": "6",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "white,pearl,satin,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/white-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-PRLW-W-25",
    "name": "Pearl White 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "White,25g",
    "tagline": "Elegant satin finish",
    "description": "Shimmering white color, pearl effect, pure",
    "otherDetails": "25g jar, satin finish",
    "mrp": "20",
    "sale": "12",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "white,pearl,satin,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/white-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-PRLW-W-50",
    "name": "Pearl White 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "White,50g",
    "tagline": "Elegant satin finish",
    "description": "Shimmering white color, pearl effect, pure",
    "otherDetails": "50g jar, satin finish",
    "mrp": "35",
    "sale": "22",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "white,pearl,satin,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/white-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-COPP-C-10",
    "name": "Copper Sunset 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Copper,10g",
    "tagline": "Warm autumnal glow",
    "description": "Antique copper color, metallic, rust-resistant",
    "otherDetails": "10g jar, metal finish",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "copper,sunset,metallic,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/copper-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-COPP-C-25",
    "name": "Copper Sunset 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Copper,25g",
    "tagline": "Warm autumnal glow",
    "description": "Antique copper color, metallic, rust-resistant",
    "otherDetails": "25g jar, metal finish",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "copper,sunset,metallic,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/copper-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-COPP-C-50",
    "name": "Copper Sunset 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Copper,50g",
    "tagline": "Warm autumnal glow",
    "description": "Antique copper color, metallic, rust-resistant",
    "otherDetails": "50g jar, metal finish",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "copper,sunset,metallic,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/copper-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-VIO-V-10",
    "name": "Violet Dream 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Violet,10g",
    "tagline": "Royal purple magic",
    "description": "Mystic violet color, shimmer, fade-resistant",
    "otherDetails": "10g jar, deep violet",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "violet,purple,shimmer,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/violet-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-VIO-V-25",
    "name": "Violet Dream 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Violet,25g",
    "tagline": "Royal purple magic",
    "description": "Mystic violet color, shimmer, fade-resistant",
    "otherDetails": "25g jar, deep violet",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "violet,purple,shimmer,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/violet-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-VIO-V-50",
    "name": "Violet Dream 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Violet,50g",
    "tagline": "Royal purple magic",
    "description": "Mystic violet color, shimmer, fade-resistant",
    "otherDetails": "50g jar, deep violet",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "violet,purple,shimmer,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/violet-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-TURQ-T-10",
    "name": "Turquoise 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Turquoise,10g",
    "tagline": "Tropical beach vibes",
    "description": "Bright turquoise color, sea-foam effect",
    "otherDetails": "10g jar, tropical",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "turquoise,cyan,beach,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/turquoise-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-TURQ-T-25",
    "name": "Turquoise 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Turquoise,25g",
    "tagline": "Tropical beach vibes",
    "description": "Bright turquoise color, sea-foam effect",
    "otherDetails": "25g jar, tropical",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "turquoise,cyan,beach,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/turquoise-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-TURQ-T-50",
    "name": "Turquoise 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Turquoise,50g",
    "tagline": "Tropical beach vibes",
    "description": "Bright turquoise color, sea-foam effect",
    "otherDetails": "50g jar, tropical",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "turquoise,cyan,beach,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/turquoise-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RGOL-RG-10",
    "name": "Rose Gold 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Rose Gold,10g",
    "tagline": "Blush metallic luxury",
    "description": "Soft pink-gold color, high luster, trendy",
    "otherDetails": "10g jar, luxury finish",
    "mrp": "12",
    "sale": "10",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "rose gold,pink,metallic,resin,mica",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/rosegold-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RGOL-RG-25",
    "name": "Rose Gold 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Rose Gold,25g",
    "tagline": "Blush metallic luxury",
    "description": "Soft pink-gold color, high luster, trendy",
    "otherDetails": "25g jar, luxury finish",
    "mrp": "24",
    "sale": "18",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "rose gold,pink,metallic,resin,mica",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/rosegold-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-RGOL-RG-50",
    "name": "Rose Gold 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Rose Gold,50g",
    "tagline": "Blush metallic luxury",
    "description": "Soft pink-gold color, high luster, trendy",
    "otherDetails": "50g jar, luxury finish",
    "mrp": "40",
    "sale": "32",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "rose gold,pink,metallic,resin,mica",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/rosegold-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-LAVN-L-10",
    "name": "Lavender 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Lavender,10g",
    "tagline": "Calm floral tones",
    "description": "Soft lavender color, pastel shimmer",
    "otherDetails": "10g jar, floral",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "lavender,purple,pastel,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/lavender-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-LAVN-L-25",
    "name": "Lavender 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Lavender,25g",
    "tagline": "Calm floral tones",
    "description": "Soft lavender color, pastel shimmer",
    "otherDetails": "25g jar, floral",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "lavender,purple,pastel,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/lavender-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-LAVN-L-50",
    "name": "Lavender 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Lavender,50g",
    "tagline": "Calm floral tones",
    "description": "Soft lavender color, pastel shimmer",
    "otherDetails": "50g jar, floral",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "lavender,purple,pastel,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/lavender-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-ELEM-EL-10",
    "name": "Electric Lemon 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Yellow,10g",
    "tagline": "Brightest neon glow",
    "description": "Neon yellow color, high visibility",
    "otherDetails": "10g jar, neon",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "yellow,lemon,neon,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/lemon-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-ELEM-EL-25",
    "name": "Electric Lemon 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Yellow,25g",
    "tagline": "Brightest neon glow",
    "description": "Neon yellow color, high visibility",
    "otherDetails": "25g jar, neon",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "yellow,lemon,neon,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/lemon-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-ELEM-EL-50",
    "name": "Electric Lemon 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Yellow,50g",
    "tagline": "Brightest neon glow",
    "description": "Neon yellow color, high visibility",
    "otherDetails": "50g jar, neon",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "yellow,lemon,neon,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/lemon-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-SBLU-SB-10",
    "name": "Sky Blue 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Sky Blue,10g",
    "tagline": "Clear day sky",
    "description": "Light blue color, shimmering, calm",
    "otherDetails": "10g jar, sky",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "sky blue,light blue,mica,resin",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/skyblue-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-SBLU-SB-25",
    "name": "Sky Blue 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Sky Blue,25g",
    "tagline": "Clear day sky",
    "description": "Light blue color, shimmering, calm",
    "otherDetails": "25g jar, sky",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "sky blue,light blue,mica,resin",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/skyblue-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-SBLU-SB-50",
    "name": "Sky Blue 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Sky Blue,50g",
    "tagline": "Clear day sky",
    "description": "Light blue color, shimmering, calm",
    "otherDetails": "50g jar, sky",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "sky blue,light blue,mica,resin",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/skyblue-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-BRNZ-BZ-10",
    "name": "Bronze 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Bronze,10g",
    "tagline": "Antique classic metal",
    "description": "Deep bronze color, metallic, heavy luster",
    "otherDetails": "10g jar, bronze",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "bronze,metallic,resin,pigment,dark",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/bronze-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-BRNZ-BZ-25",
    "name": "Bronze 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Bronze,25g",
    "tagline": "Antique classic metal",
    "description": "Deep bronze color, metallic, heavy luster",
    "otherDetails": "25g jar, bronze",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "bronze,metallic,resin,pigment,dark",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/bronze-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-BRNZ-BZ-50",
    "name": "Bronze 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Bronze,50g",
    "tagline": "Antique classic metal",
    "description": "Deep bronze color, metallic, heavy luster",
    "otherDetails": "50g jar, bronze",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "bronze,metallic,resin,pigment,dark",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/bronze-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-HPIN-HP-10",
    "name": "Hot Pink 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Pink,10g",
    "tagline": "Pop of vibrant pink",
    "description": "Bright pink color, energetic, bold",
    "otherDetails": "10g jar, vibrant",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "hot pink,magenta,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/pink-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-HPIN-HP-25",
    "name": "Hot Pink 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Pink,25g",
    "tagline": "Pop of vibrant pink",
    "description": "Bright pink color, energetic, bold",
    "otherDetails": "25g jar, vibrant",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "hot pink,magenta,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/pink-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-HPIN-HP-50",
    "name": "Hot Pink 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Pink,50g",
    "tagline": "Pop of vibrant pink",
    "description": "Bright pink color, energetic, bold",
    "otherDetails": "50g jar, vibrant",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "hot pink,magenta,resin,pigment",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/pink-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-TEAL-TL-10",
    "name": "Teal 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Teal,10g",
    "tagline": "Sophisticated blue-green",
    "description": "Deep teal color, ocean-themed, elegant",
    "otherDetails": "10g jar, teal",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "teal,cyan,green-blue,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/teal-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-TEAL-TL-25",
    "name": "Teal 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Teal,25g",
    "tagline": "Sophisticated blue-green",
    "description": "Deep teal color, ocean-themed, elegant",
    "otherDetails": "25g jar, teal",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "teal,cyan,green-blue,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/teal-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-TEAL-TL-50",
    "name": "Teal 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Teal,50g",
    "tagline": "Sophisticated blue-green",
    "description": "Deep teal color, ocean-themed, elegant",
    "otherDetails": "50g jar, teal",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "teal,cyan,green-blue,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/teal-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-CHOC-CB-10",
    "name": "Chocolate Brown 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Brown,10g",
    "tagline": "Rich earthy chocolate",
    "description": "Deep brown color, earthy, wood-like",
    "otherDetails": "10g jar, coffee",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "brown,chocolate,earth,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/brown-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-CHOC-CB-25",
    "name": "Chocolate Brown 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Brown,25g",
    "tagline": "Rich earthy chocolate",
    "description": "Deep brown color, earthy, wood-like",
    "otherDetails": "25g jar, coffee",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "brown,chocolate,earth,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/brown-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-CHOC-CB-50",
    "name": "Chocolate Brown 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Brown,50g",
    "tagline": "Rich earthy chocolate",
    "description": "Deep brown color, earthy, wood-like",
    "otherDetails": "50g jar, coffee",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "brown,chocolate,earth,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/brown-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-CHAM-CH-10",
    "name": "Champagne 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Champagne,10g",
    "tagline": "Bubbly luxury gold",
    "description": "Soft gold color, sparkling, bridal",
    "otherDetails": "10g jar, light gold",
    "mrp": "12",
    "sale": "10",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "champagne,gold,sparkle,resin,mica",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/champagne-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-CHAM-CH-25",
    "name": "Champagne 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Champagne,25g",
    "tagline": "Bubbly luxury gold",
    "description": "Soft gold color, sparkling, bridal",
    "otherDetails": "25g jar, light gold",
    "mrp": "24",
    "sale": "18",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "champagne,gold,sparkle,resin,mica",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/champagne-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-CHAM-CH-50",
    "name": "Champagne 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Champagne,50g",
    "tagline": "Bubbly luxury gold",
    "description": "Soft gold color, sparkling, bridal",
    "otherDetails": "50g jar, light gold",
    "mrp": "40",
    "sale": "30",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "champagne,gold,sparkle,resin,mica",
    "trending": "Yes",
    "delivery": "3-5 Days",
    "images": [
      "img/champagne-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-LIME-LM-10",
    "name": "Lime Green 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Lime,10g",
    "tagline": "Fresh citrus pop",
    "description": "Bright lime color, neon shimmer, citrus",
    "otherDetails": "10g jar, fresh",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "lime,green,neon,citrus,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/lime-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-LIME-LM-25",
    "name": "Lime Green 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Lime,25g",
    "tagline": "Fresh citrus pop",
    "description": "Bright lime color, neon shimmer, citrus",
    "otherDetails": "25g jar, fresh",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "lime,green,neon,citrus,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/lime-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-LIME-LM-50",
    "name": "Lime Green 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Lime,50g",
    "tagline": "Fresh citrus pop",
    "description": "Bright lime color, neon shimmer, citrus",
    "otherDetails": "50g jar, fresh",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "lime,green,neon,citrus,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/lime-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-WINE-WR-10",
    "name": "Wine Red 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Wine Red,10g",
    "tagline": "Sophisticated burgundy",
    "description": "Deep burgundy color, velvet shimmer",
    "otherDetails": "10g jar, wine",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "wine red,burgundy,dark red,resin",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/winered-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-WINE-WR-25",
    "name": "Wine Red 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Wine Red,25g",
    "tagline": "Sophisticated burgundy",
    "description": "Deep burgundy color, velvet shimmer",
    "otherDetails": "25g jar, wine",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "wine red,burgundy,dark red,resin",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/winered-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-WINE-WR-50",
    "name": "Wine Red 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Wine Red,50g",
    "tagline": "Sophisticated burgundy",
    "description": "Deep burgundy color, velvet shimmer",
    "otherDetails": "50g jar, wine",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "wine red,burgundy,dark red,resin",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/winered-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-GGRY-GY-10",
    "name": "Graphite Gray 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Gray,10g",
    "tagline": "Industrial steel look",
    "description": "Charcoal gray color, metallic, smoke",
    "otherDetails": "10g jar, graphite",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "gray,graphite,charcoal,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/gray-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-GGRY-GY-25",
    "name": "Graphite Gray 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Gray,25g",
    "tagline": "Industrial steel look",
    "description": "Charcoal gray color, metallic, smoke",
    "otherDetails": "25g jar, graphite",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "gray,graphite,charcoal,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/gray-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-GGRY-GY-50",
    "name": "Graphite Gray 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Gray,50g",
    "tagline": "Industrial steel look",
    "description": "Charcoal gray color, metallic, smoke",
    "otherDetails": "50g jar, graphite",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "gray,graphite,charcoal,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/gray-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-MINT-MN-10",
    "name": "Mint Green 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Mint,10g",
    "tagline": "Refreshing cool green",
    "description": "Pale green color, pastel, refreshing",
    "otherDetails": "10g jar, mint",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "mint,green,pastel,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/mint-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-MINT-MN-25",
    "name": "Mint Green 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Mint,25g",
    "tagline": "Refreshing cool green",
    "description": "Pale green color, pastel, refreshing",
    "otherDetails": "25g jar, mint",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "mint,green,pastel,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/mint-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-MINT-MN-50",
    "name": "Mint Green 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Mint,50g",
    "tagline": "Refreshing cool green",
    "description": "Pale green color, pastel, refreshing",
    "otherDetails": "50g jar, mint",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "mint,green,pastel,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/mint-50.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-MAGE-MA-10",
    "name": "Magenta 10g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Magenta,10g",
    "tagline": "Fierce purple-pink",
    "description": "Deep pink color, bold, intense",
    "otherDetails": "10g jar, magenta",
    "mrp": "10",
    "sale": "8",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "magenta,pink,purple,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/magenta-10.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-MAGE-MA-25",
    "name": "Magenta 25g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Magenta,25g",
    "tagline": "Fierce purple-pink",
    "description": "Deep pink color, bold, intense",
    "otherDetails": "25g jar, magenta",
    "mrp": "20",
    "sale": "15",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "magenta,pink,purple,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/magenta-25.jpg"
    ],
    "vid": ""
  },
  {
    "id": "MICA-MASTER",
    "sku": "SKU-MAGE-MA-50",
    "name": "Magenta 50g",
    "category": "Pigments",
    "subcategory": "Mica Powder",
    "tagweb": "resin,color",
    "brand": "ResinArt Pro",
    "attrName": "Color,Weight",
    "attrValue": "Magenta,50g",
    "tagline": "Fierce purple-pink",
    "description": "Deep pink color, bold, intense",
    "otherDetails": "50g jar, magenta",
    "mrp": "35",
    "sale": "28",
    "stock": "instock",
    "minOrder": "1",
    "isKit": "FALSE",
    "kitName": "N/A",
    "kitComponents": "N/A",
    "keyword": "magenta,pink,purple,resin,mica",
    "trending": "No",
    "delivery": "3-5 Days",
    "images": [
      "img/magenta-50.jpg"
    ],
    "vid": ""
  }
];

window.dispatchEvent(new Event('db_ready'));
